More mod compatibility
TelepathicGrunt/Bumblezone pull request #438
Opened 2024-08-31 20:03 UTC by Cicopath

This PR adds more compatibility for mods.

Notable additions:
* Revival recipes using Regions Unexplored and Hybrid Aquatic
* Color randomizer recipes using MC Dungeon Armors, Luphie's Cluttered Mod, Swampier Swamps, and Create Railways

Other additions:
* Added certain entities, blocks, and items to tags for expanded mod compatibility

Notes: Everything should work fine. The only issues I had were with the color randomizer recipes that used `#the_bumblezone:modded/[info]` item tags, but I think it might've just been a loading issue? The code itself is valid.

2024-09-01 01:43 UTC, TelepathicGrunt requested changes

2024-09-01 01:43 UTC, TelepathicGrunt commented on common/src/main/resources/data/the_bumblezone/tags/block/crystalline_flower/can_be_placed_on.json
> +      "id": "malum:block_of_blazing_quartz",
I dont think this looks very crystal-like like amethyst does. I would not let crystalline flower be placable on that block by default imo

2024-09-01 01:43 UTC, TelepathicGrunt commented on common/src/main/resources/data/the_bumblezone/tags/entity_type/hanging_garden/initial_spawn_entities.json
> +      "id": "betternether:firefly",
Betternether firefly doesnt look like a bug nor a firefly. It does not fit into hanging garden's look. Please remove this
![image](https://github.com/user-attachments/assets/ae4103e9-fd65-4a7f-a801-6a90912f9096)

2024-09-01 01:43 UTC, TelepathicGrunt commented on common/src/main/resources/data/the_bumblezone/tags/entity_type/string_curtains/blocks_pathfinding_for_non_bee_mob.json
> +      "id": "betternether:firefly",
Since the mob doesnt look like a bug to me, string curtains should not block it imo. It's for blocking flying bugs

2024-09-04 00:00 UTC, Cicopath commented on common/src/main/resources/data/the_bumblezone/tags/block/crystalline_flower/can_be_placed_on.json
> +      "id": "malum:block_of_blazing_quartz",
Ah, I didn't realize it was just amethyst-like blocks. I saw some quartz blocks in there so I thought both amethyst _and_ quartz blocks were intended. Looked closer and I realize some of the quartz blocks mentioned are actually amethyst-like. Whoops!

Looking at amethyst-like blocks in my modpack, there is a mod called Chipped that adds amethyst design variants, which currently aren't added to this tag. Below is a picture of just a few blocks—there are about 64 blocks total, but they're all listed under a block tag added by the mod. Would you like these amethyst block variants included in this tag?

![image](https://github.com/user-attachments/assets/e2dc56fd-b01e-483a-9f19-78ccec382dcb)

2024-09-04 00:02 UTC, Cicopath commented on common/src/main/resources/data/the_bumblezone/tags/entity_type/hanging_garden/initial_spawn_entities.json
> +      "id": "betternether:firefly",
Do you want me to leave BetterEnd's silk moth in the tag, or remove it too?

![image](https://github.com/user-attachments/assets/f2a44c65-59ca-4786-9387-de744d1e99eb)

2024-09-04 00:04 UTC, TelepathicGrunt commented on common/src/main/resources/data/the_bumblezone/tags/block/crystalline_flower/can_be_placed_on.json
> +      "id": "malum:block_of_blazing_quartz",
hard to say as those amethyst blocks are more polished/flat. I was going for visible crystals. Well trying to. I think the tag is fine currently as it already has a lot of blocks. You can always add more in your pack if you feel your pack should allow crystalline flower on new blocks

2024-09-04 00:05 UTC, TelepathicGrunt commented on common/src/main/resources/data/the_bumblezone/tags/entity_type/hanging_garden/initial_spawn_entities.json
> +      "id": "betternether:firefly",
Keep that. That's bug-like and more recognizable than the better nether "firefly" lol

2024-09-04 01:21 UTC, Cicopath commented on common/src/main/resources/data/the_bumblezone/tags/block/crystalline_flower/can_be_placed_on.json
> +      "id": "malum:block_of_blazing_quartz",
Removed the Blazing Quartz

2024-09-04 01:21 UTC, Cicopath commented on common/src/main/resources/data/the_bumblezone/tags/entity_type/hanging_garden/initial_spawn_entities.json
> +      "id": "betternether:firefly",
Up close, the firefly looks both adorable and freaky lol. Removed the firefly.

2024-09-04 01:21 UTC, Cicopath commented on common/src/main/resources/data/the_bumblezone/tags/entity_type/string_curtains/blocks_pathfinding_for_non_bee_mob.json
> +      "id": "betternether:firefly",
Removed the firefly

2024-09-04 01:22 UTC, Cicopath commented
Need to go through and edit a few of the Luphie color randomizer recipes due to them having 3 items or less

2024-09-04 01:46 UTC, Cicopath commented
Oh dear, those are a lot of listed commits 😰 wish there was a way to compact all of that on the web browser to make it more sightly...

Regardless, all of the recipes that had little items or weren't related to color have been removed.

Are you fine with the randomizer recipes for the woods, doors, etc. (e.g. https://github.com/Cicopath/Bumblezone/blob/1.21-Arch/common/src/main/resources/data/the_bumblezone/tags/item/modded/luphieclutteredmod_logs.json), or would you prefer them removed? In the mod, in order to make these colored woods, you have to craft them with their respective dye (some of them are crafted with items other than dye, such as flowers or glowstone dust).

![image](https://github.com/user-attachments/assets/fa4a9bf1-a729-4480-89a0-9046f72a0a6f)
![image](https://github.com/user-attachments/assets/a988988a-4964-484e-9c8e-06dcf13ddeca)
![image](https://github.com/user-attachments/assets/83f759c6-6e31-4d08-bb15-e18b8450d63d)

2024-09-05 01:56 UTC, TelepathicGrunt commented
If there was wood for every dye color, then it would make sense to do color randomizing. But with just 4 colors, not worth imo

2024-09-05 03:55 UTC, Cicopath commented
Alright, that should be it for housekeeping recipes and tags that don't fit with how the colored randomized trades are intended 🙏 

Since these are not technically added from 1.21, I guess this PR either can stay open until they all update or merge and the IDs can be changed after (probably the former for now).

I'll add this data to the 1.20.x-Arch branch, the version from which it originates, and create a separate PR for that.

2024-09-07 12:03 UTC, TelepathicGrunt approved these changes

2024-09-07 12:04 UTC, merged