Add zh_cn translation and add missing Sugar Water fluid's localization.
TelepathicGrunt/Bumblezone pull request #74
Opened 2021-08-31 05:15 UTC by mcBegins2Snow

2021-08-31 13:37 UTC, TelepathicGrunt requested changes
It looks good! I just have two things that probably should be adjusted before I merge this. The two things are below:

2021-08-31 13:37 UTC, TelepathicGrunt commented on src/main/resources/assets/the_bumblezone/lang/zh_cn.json
> +	"block.the_bumblezone.sticky_honey_redstone":"黏性蜂蜜红石粉",
Is this right? When I double check the translation, deepl says "黏性蜂蜜红石粉" is "Viscous honey red stone powder" but it's more of a residue. Not really a powder. For example, let's say I spilled some syrup and it dries out completely. The stuff that is left is an extremely sticky substance attached to the surface. A residue leftover from the syrup. That's is what I was going for. 

Would this be a better translation closer to my original meaning? Or is it incorrect? "黏性蜂蜜红石残留物"

2021-08-31 13:37 UTC, TelepathicGrunt commented on src/main/resources/assets/the_bumblezone/lang/zh_cn.json
> +	"item.the_bumblezone.music_disc_flight_of_the_bumblebee_rimsky_korsakov.desc":"里姆斯基·柯萨科夫 - 野蜂飞舞",
This is the name of the song and its creator. I believe this is better when not translated. What do you think?

2021-09-01 01:11 UTC, mcBegins2Snow commented on src/main/resources/assets/the_bumblezone/lang/zh_cn.json
> +	"block.the_bumblezone.sticky_honey_redstone":"黏性蜂蜜红石粉",
changed

2021-09-01 01:13 UTC, mcBegins2Snow commented on src/main/resources/assets/the_bumblezone/lang/zh_cn.json
> +	"item.the_bumblezone.music_disc_flight_of_the_bumblebee_rimsky_korsakov.desc":"里姆斯基·柯萨科夫 - 野蜂飞舞",
change revoked

2021-09-01 05:16 UTC, TelepathicGrunt commented
Awesome thanks! will merge and it'll be included in bumblezone's next update

2021-09-01 05:16 UTC, merged

2021-09-01 10:35 UTC, mcBegins2Snow commented
I don't mind.